// Catálogo de sets/colecciones del TCG Pokémon, para autocompletar el
// campo "Colección / set" al publicar una carta. No es exhaustivo (hay
// también sets promocionales, McDonald's, etc.) por eso el campo sigue
// aceptando texto libre — esto solo sugiere los nombres más comunes.

export const POKEMON_SET_ERAS = [
  {
    era: "Scarlet & Violet",
    sets: [
      "Scarlet & Violet Base",
      "Paldea Evolved",
      "Obsidian Flames",
      "151",
      "Paradox Rift",
      "Paldean Fates",
      "Temporal Forces",
      "Twilight Masquerade",
      "Shrouded Fable",
      "Stellar Crown",
      "Surging Sparks",
      "Prismatic Evolutions",
      "Journey Together",
      "Destined Rivals",
    ],
  },
  {
    era: "Sword & Shield",
    sets: [
      "Sword & Shield Base",
      "Rebel Clash",
      "Darkness Ablaze",
      "Champion's Path",
      "Vivid Voltage",
      "Shining Fates",
      "Battle Styles",
      "Chilling Reign",
      "Evolving Skies",
      "Celebrations",
      "Fusion Strike",
      "Brilliant Stars",
      "Astral Radiance",
      "Pokémon GO",
      "Lost Origin",
      "Silver Tempest",
      "Crown Zenith",
    ],
  },
  {
    era: "Sun & Moon",
    sets: [
      "Sun & Moon Base",
      "Guardians Rising",
      "Burning Shadows",
      "Shining Legends",
      "Crimson Invasion",
      "Ultra Prism",
      "Forbidden Light",
      "Celestial Storm",
      "Dragon Majesty",
      "Lost Thunder",
      "Team Up",
      "Detective Pikachu",
      "Unbroken Bonds",
      "Unified Minds",
      "Hidden Fates",
      "Cosmic Eclipse",
    ],
  },
  {
    era: "XY",
    sets: [
      "XY Base",
      "Flashfire",
      "Furious Fists",
      "Phantom Forces",
      "Primal Clash",
      "Double Crisis",
      "Roaring Skies",
      "Ancient Origins",
      "BREAKthrough",
      "BREAKpoint",
      "Generations",
      "Fates Collide",
      "Steam Siege",
      "Evolutions",
    ],
  },
  {
    era: "Black & White",
    sets: [
      "Black & White Base",
      "Emerging Powers",
      "Noble Victories",
      "Next Destinies",
      "Dark Explorers",
      "Dragons Exalted",
      "Dragon Vault",
      "Boundaries Crossed",
      "Plasma Storm",
      "Plasma Freeze",
      "Plasma Blast",
      "Legendary Treasures",
    ],
  },
  {
    era: "HeartGold & SoulSilver",
    sets: [
      "HeartGold & SoulSilver Base",
      "Unleashed",
      "Undaunted",
      "Triumphant",
      "Call of Legends",
    ],
  },
  {
    era: "Platinum",
    sets: ["Platinum Base", "Rising Rivals", "Supreme Victors", "Arceus"],
  },
  {
    era: "Diamond & Pearl",
    sets: [
      "Diamond & Pearl Base",
      "Mysterious Treasures",
      "Secret Wonders",
      "Great Encounters",
      "Majestic Dawn",
      "Legends Awakened",
      "Stormfront",
    ],
  },
  {
    era: "EX",
    sets: [
      "EX Ruby & Sapphire",
      "EX Sandstorm",
      "EX Dragon",
      "EX Team Magma vs Team Aqua",
      "EX Hidden Legends",
      "EX FireRed & LeafGreen",
      "EX Team Rocket Returns",
      "EX Deoxys",
      "EX Emerald",
      "EX Unseen Forces",
      "EX Delta Species",
      "EX Legend Maker",
      "EX Holon Phantoms",
      "EX Crystal Guardians",
      "EX Dragon Frontiers",
      "EX Power Keepers",
    ],
  },
  {
    era: "WOTC (clásicos)",
    sets: [
      "Base Set",
      "Jungle",
      "Fossil",
      "Base Set 2",
      "Team Rocket",
      "Gym Heroes",
      "Gym Challenge",
      "Neo Genesis",
      "Neo Discovery",
      "Neo Revelation",
      "Neo Destiny",
      "Legendary Collection",
      "Expedition Base Set",
      "Aquapolis",
      "Skyridge",
    ],
  },
];

export const POKEMON_SETS = POKEMON_SET_ERAS.flatMap((e) => e.sets);
